version: '3'
services:
  postgres:
    container_name: postgres-user
    image: postgres:16-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=person-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Vulsan2001
    volumes:
      - user:/var/lib/postgresql/data
  app:
    container_name: users
    image: users
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/person-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Vulsan2001
    links:
      - postgres

volumes:
  user: