version: '3'
services:
  postgres:
    container_name: postgres-monitoring
    image: postgres:16-alpine3.18
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=monitoring-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Vulsan2001
    volumes:
      - device:/var/lib/postgresql/data
  app:
    container_name: monitoring
    image: monitoring
    build: .
    ports:
      - "8001:8001"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/monitoring-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Vulsan2001
    links:
      - postgres

volumes:
  device: